version: "3.8"

services:
    app:
        image: bitbarg:0.6
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app-network
        ports:
            - "8080:8080"

    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        networks:
            - app-network

    db:
        image: postgres:13
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456789
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    postgres-data:
        driver: local
